# 折线图配置
[line]
[line.acc]
labels1 = 'train acc'
labels2 = 'test acc'
xlabel = 'epochs'
ylabel = 'acc'
filename = 'line_acc.png' # 实验名 + filename

[line.loss]
labels1 = 'train loss'
labels2 = 'test loss'
xlabel = 'epochs'
ylabel = 'loss'
filename = 'line_loss.png'

# 柱状图配置
[bar]
[bar.group]
figsize = [15, 10]
xlabel = 'Phone ID'
ylabel = 'number of symbols'
title = 'number of train and test symbols'
filename = 'bar_group.png'

[bar.single.train]
xlabel = 'Phone ID'
ylabel = 'number of symbols'
title = 'number of train symbols'
filename = 'bar_single_train.png'

[bar.single.test]
xlabel = 'Phone ID'
ylabel = 'number of symbols'
title = 'number of test symbols'
filename = 'bar_single_test.png'

# 混淆矩阵配置
[cm]
filename = 'cm.png'
